export { default as setCookie } from './setCookie';
export { default as activeSection } from './activeSection';
export { default as currentTab } from './currentTab';
export { default as stripURL } from './stripURL';
export { default as getStoreURL } from './getStoreURL';
export { default as runOnTab } from './runOnTab';
export { default as isPDP } from './isPDP';
export { default as getVtexInfo } from './getVtexInfo';
export { default as dispatchVtexInfo } from './dispatchVtexInfo';
